[package]
name = "integration-tests-bindings"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dart-api-dl="0.3.0"
async-bindgen = "0.1.0"
once_cell = "1.8.0"
thiserror = "1.0.30"

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "=0.20.0"
