[package]
name = "integration-tests-bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
async-bindgen = "0.1.0"
once_cell = "1.8.0"
thiserror = "1.0.30"

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "=0.20.0"
