[package]
name = "async-bindgen-gen-dart"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
handlebars = "4.2.0"
heck = "0.4.0"
once_cell = "1.9.0"
regex = "1.5.4"
serde = { version = "1.0.133", features = ["derive"] }
structopt = "0.3.25"
