/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initializes the dart api.
 *
 * Is safe to be called multiple times and form multiple
 * thread.
 *
 * # Safety
 *
 * Must be called with a pointer produced by dart using
 * `NativeApi.initializeApiDLData`.
 */
uint8_t async_bindgen_dart_init_api__async_api(void *init_data);

/**
 * Wrapper for initiating the call to an async function.
 */
uint8_t async_bindgen_dart_c__async_api__add(uint8_t x,
                                             uint8_t y,
                                             DartPortId async_bindgen_dart_port_id,
                                             int64_t async_bindgen_dart_completer_id);

/**
 * Extern "C"  wrapper delegating to `PreparedCompleter::extract_result()`.
 *
 * # Safety
 *
 * See the language specific version of `PreparedCompleter::extract_result()`.
 */
uint8_t async_bindgen_dart_r__async_api__add(int64_t handle);

/**
 * Wrapper for initiating the call to an async function.
 */
uint8_t async_bindgen_dart_c__async_api__sub(uint8_t x,
                                             uint8_t y,
                                             DartPortId async_bindgen_dart_port_id,
                                             int64_t async_bindgen_dart_completer_id);

/**
 * Extern "C"  wrapper delegating to `PreparedCompleter::extract_result()`.
 *
 * # Safety
 *
 * See the language specific version of `PreparedCompleter::extract_result()`.
 */
uint8_t async_bindgen_dart_r__async_api__sub(int64_t handle);

/**
 * Initializes the dart api.
 *
 * Is safe to be called multiple times and form multiple
 * thread.
 *
 * # Safety
 *
 * Must be called with a pointer produced by dart using
 * `NativeApi.initializeApiDLData`.
 */
uint8_t async_bindgen_dart_init_api__api2(void *init_data);

/**
 * Wrapper for initiating the call to an async function.
 */
uint8_t async_bindgen_dart_c__api2__get_the_byte(DartPortId async_bindgen_dart_port_id,
                                                 int64_t async_bindgen_dart_completer_id);

/**
 * Extern "C"  wrapper delegating to `PreparedCompleter::extract_result()`.
 *
 * # Safety
 *
 * See the language specific version of `PreparedCompleter::extract_result()`.
 */
uint8_t async_bindgen_dart_r__api2__get_the_byte(int64_t handle);
