[package]
name = "easync-rust-dart-io-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dart-api-dl = "0.3.0"
async-std = "1.10.0"