[package]
name = "async-bindgen-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.3.3"
once_cell = "1.8.0"
proc-macro2 = "1.0.29"
quote = "1.0.10"
syn = { version = "1.0.10", features = ["full", "extra-traits"] }
