[package]
name = "async-bindgen-derive"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
heck = "0.4.0"
once_cell = "1.9.0"
proc-macro2 = "1.0.36"
quote = "1.0.14"
syn = { version = "1.0.85", features = ["full", "extra-traits"] }
