[package]
name = "async-bindgen-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version="1.0.10", features=["full", "extra-traits"] }
quote = "1.0.10"
proc-macro2 = "1.0.29"
once_cell = "1.8.0"
heck = "0.3.3"