[package]
name = "easync-core"
version = "0.1.0"
edition = "2021"

[features]
dart-native = []

[dependencies]
static_assertions = "1.1.0"
futures-channel = "0.3.7"
once_cell = "1.8.0"
dart-api-dl = "0.3.0"