#[rustfmt::skip]
mod async_api;
#[rustfmt::skip]
mod api2;

//yes the struct is generated by us
// as well as a `pub use ::async_bindgen_bindings::<name>::*;`
// we use that as we don't really know where in the file tree this
// file is.
#[async_bindgen::api]
impl AsyncApi {
    pub async fn add(x: u8, y: u8) -> u8 {
        x + y
    }

    pub async fn sub(x: u8, y: u8) -> u8 {
        x - y
    }
}

#[async_bindgen::api]
impl Api2 {
    pub async fn get_the_byte() -> u8 {
        12
    }
}
