[package]
name = "async-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
async-bindgen-derive = { path = "../async-bindgen-derive" }
async-std = "1.10.0"
static_assertions = "1.1.0"
thiserror = "1.0.30"
xayn-dart-api-dl = "0.3.0"
