name: Rust CI

on:
  push:
    paths:
      - '.github/workflows/rust_ci.yml'
      - 'async-bindgen/**'
      - 'async-bindgen-derive/**'
      - 'async-bindgen-gen-dart/**'
      - 'integration-tests-bindings/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_NIGHTLY: nightly-2021-09-09
  RUST_WORKSPACE: ${{ github.workspace }}/
  RUSTFLAGS: "-D warnings"
  DISABLE_AUTO_DART_FFIGEN: 1

jobs:
  cargo-format:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup toolchain install ${{ env.RUST_NIGHTLY }} --component rustfmt

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1

      - name: cargo fmt
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo +${{ env.RUST_NIGHTLY }} fmt --all -- --check

  cargo-sort:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install cargo-sort
        uses: ./.ci/install-cargo-sort

      - name: cargo sort
        run: cargo sort --grouped --workspace --check

  cargo-clippy:
    runs-on: ubuntu-20.04
    needs: cargo-format
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1

      - name: cargo clippy
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: |
          # Workaround for code-gen bug
          cargo check --quiet 2>/dev/null || :
          cargo clippy --all-targets -- --deny warnings

  cargo-test:
    timeout-minutes: 20
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1

      - name: Run tests
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: |
          # Workaround for code-gen bug
          cargo check --quiet 2>/dev/null || :
          cargo test --all-targets --quiet
          cargo test --doc --quiet

  # this is an helper that needs all the real leafs of the workflow.
  # It makes easier notify_main_failure because we only need to check
  # for this job
  ci-ok:
    name: ci-ok
    needs:
      - cargo-test
    runs-on: ubuntu-20.04
    steps:
      - name: Nothing to do
        run: echo "Helper job nothing to do"

  notify-main-failure:
    name: notify-main-failure
    needs: ci-ok
    # always() allows to run even if ci-ok is not successful
    # we only want this to run on the main branch
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failure
        if: needs.ci-ok.result != 'success'
        uses: 8398a7/action-slack@b17d9de8e9ed64b041e4fac845d6fdb2be6b9b04 # v3.11.0
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              attachments: [{
                title: 'Main CI failed :warning:',
                color: 'danger',
                text: `CI: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
